# Generated by Django 3.2.11 on 2022-11-22 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_img',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
