# Generated by Django 3.2.11 on 2022-11-19 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
        ('accounts', '0006_alter_user_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bookmark_movies',
            field=models.ManyToManyField(related_name='bookmark_users', to='movies.Movie'),
        ),
    ]
