# Generated by Django 3.2.11 on 2022-11-19 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_bookmark_movies'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='bookmark_movies',
            new_name='bookmarks',
        ),
    ]
