# Generated by Django 3.2.11 on 2022-11-16 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='name_origin',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
