# Generated by Django 3.2.11 on 2022-11-16 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='original_language',
        ),
    ]
