# Generated by Django 3.2.11 on 2022-11-17 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='backdrop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='movies.backdrop'),
        ),
    ]
