# Generated by Django 3.2.11 on 2022-11-17 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
        ('community', '0002_alter_review_backdrop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='backdrop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='movies.backdrop'),
            preserve_default=False,
        ),
    ]
